---
paths:

  # experimental
  /individuals:
    post:
      description: |
        Get response to a beacon query for individual information.
      operationId: postIndividualResponse
      tags:
        - Endpoints
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Request'
        required: true
      responses:
        '200':
          description: |
            Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IndividualResponse'
        '400':
          description: |
            Bad request (e.g. missing mandatory parameter)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IndividualResponse'
        '401':
          description: >-
            Unauthorised (e.g. when an unauthenticated user tries to access a
            protected resource)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IndividualResponse'
        '403':
          description: >-
            Forbidden (e.g. the resource is protected for all users or the user
            is authenticated but s/he is not granted for this resource)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IndividualResponse'
  /filtering_terms:
    get:
      description: |
        Receive a list of filter objects.
  /query:
    post:
      description: |
        Standard Beacon query
  /individuals/{id}:
    post:
      description: |
        Get an individual by its Id.
      operationId: postIndividualById
      tags:
        - Endpoints
      parameters:
        - name: id
          in: path
          description: Individual ID
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Request'
        required: true
      responses:
        '200':
          description: |
            Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IndividualResponse'
        '400':
          description: |
            Bad request (e.g. missing mandatory parameter)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IndividualResponse'
        '401':
          description: >-
            Unauthorised (e.g. when an unauthenticated user tries to access a
            protected resource)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IndividualResponse'
        '403':
          description: >-
            Forbidden (e.g. the resource is protected for all users or the user
            is authenticated but s/he is not granted for this resource)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IndividualResponse'
  /individuals/{id}/biosamples:
    post:
      description: |
        Get biosamples found in this individual.
      operationId: postBiosamplesByIndividualId
      tags:
        - Endpoints
      parameters:
        - name: id
          in: path
          description: Individual ID
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Request'
        required: true
      responses:
        '200':
          description: |
            Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BiosampleResponse'
        '400':
          description: |
            Bad request (e.g. missing mandatory parameter)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BiosampleResponse'
        '401':
          description: >-
            Unauthorised (e.g. when an unauthenticated user tries to access a
            protected resource)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BiosampleResponse'
        '403':
          description: >-
            Forbidden (e.g. the resource is protected for all users or the user
            is authenticated but s/he is not granted for this resource)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BiosampleResponse'
  /individuals/{id}/g_variants:
    post:
      description: |
        Get variants that have been stored for  this individual.
      operationId: postVariantsByIndividualId
      tags:
        - Endpoints
      parameters:
        - name: id
          in: path
          description: Individual ID
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Request'
        required: true
      responses:
        '200':
          description: |
            Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenomicVariantResponse'
        '400':
          description: |
            Bad request (e.g. missing mandatory parameter)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenomicVariantResponse'
        '401':
          description: >-
            Unauthorised (e.g. when an unauthenticated user tries to access a
            protected resource)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenomicVariantResponse'
        '403':
          description: >-
            Forbidden (e.g. the resource is protected for all users or the user
            is authenticated but s/he is not granted for this resource)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenomicVariantResponse'
  /biosamples:
    post:
      description: |
        Get response to a beacon query for biosample information.
      operationId: postSampleResponse
      tags:
        - Endpoints
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Request'
        required: true
      responses:
        '200':
          description: |
            Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BiosampleResponse'
        '400':
          description: |
            Bad request (e.g. missing mandatory parameter)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BiosampleResponse'
        '401':
          description: >-
            Unauthorised (e.g. when an unauthenticated user tries to access a
            protected resource)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BiosampleResponse'
        '403':
          description: >-
            Forbidden (e.g. the resource is protected for all users or the user
            is authenticated but they are not granted for this resource)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BiosampleResponse'
  /biosamples/{id}:
    post:
      description: |
        Get a biosample by its Id.
      operationId: postBiosampleById
      tags:
        - Endpoints
      parameters:
        - name: id
          in: path
          description: Biosample ID
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Request'
        required: true
      responses:
        '200':
          description: |
            Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BiosampleResponse'
        '400':
          description: |
            Bad request (e.g. missing mandatory parameter)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BiosampleResponse'
        '401':
          description: >-
            Unauthorised (e.g. when an unauthenticated user tries to access a
            protected resource)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BiosampleResponse'
        '403':
          description: >-
            Forbidden (e.g. the resource is protected for all users or the user
            is authenticated but they are not granted for this resource)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BiosampleResponse'
  /biosamples/{id}/individuals:
    post:
      description: |
        Get the individual to whom this biosample belongs to.
      operationId: postIndividualsByBiosampleId
      tags:
        - Endpoints
      parameters:
        - name: id
          in: path
          description: Biosample ID
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Request'
        required: true
      responses:
        '200':
          description: |
            Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IndividualResponse'
        '400':
          description: |
            Bad request (e.g. missing mandatory parameter)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IndividualResponse'
        '401':
          description: >-
            Unauthorised (e.g. when an unauthenticated user tries to access a
            protected resource)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IndividualResponse'
        '403':
          description: >-
            Forbidden (e.g. the resource is protected for all users or the user
            is authenticated but s/he is not granted for this resource)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IndividualResponse'
  /biosamples/{id}/g_variants:
    post:
      description: |
        Get the variants that have been stored for this biosample.
      operationId: postVariantsByBiosampleId
      tags:
        - Endpoints
      parameters:
        - name: id
          in: path
          description: Biosample ID
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Request'
        required: true
      responses:
        '200':
          description: |
            Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenomicVariantResponse'
        '400':
          description: |
            Bad request (e.g. missing mandatory parameter)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenomicVariantResponse'
        '401':
          description: >-
            Unauthorised (e.g. when an unauthenticated user tries to access a
            protected resource)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenomicVariantResponse'
        '403':
          description: >-
            Forbidden (e.g. the resource is protected for all users or the user
            is authenticated but s/he is not granted for this resource)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenomicVariantResponse'
  /g_variants:
    post:
      description: |
        Any kind of genomic query that wants to query variants.
      operationId: postGenomicVariant
      tags:
        - Endpoints
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Request'
        required: true
      responses:
        '200':
          description: |
            Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenomicVariantResponse'
        '400':
          description: |
            Bad request (e.g. missing mandatory parameter)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenomicVariantResponse'
        '401':
          description: >-
            Unauthorised (e.g. when an unauthenticated user tries to access a
            protected resource)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenomicVariantResponse'
        '403':
          description: >-
            Forbidden (e.g. the resource is protected for all users or the user
            is authenticated but s/he is not granted for this resource)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenomicVariantResponse'
  /g_variants/{id}:  
    post:
      description: |
        Get a variant by its Id.
      operationId: getGenomicVariantById
      tags:
        - Endpoints
      parameters:
        - name: id
          in: path
          description: Variant ID
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Request'
      responses:
        '200':
          description: |
            Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenomicVariantResponse'
        '400':
          description: |
            Bad request (e.g. missing mandatory parameter)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenomicVariantResponse'
        '401':
          description: >-
            Unauthorised (e.g. when an unauthenticated user tries to access a
            protected resource)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenomicVariantResponse'
        '403':
          description: >-
            Forbidden (e.g. the resource is protected for all users or the user
            is authenticated but s/he is not granted for this resource)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenomicVariantResponse'
  /g_variants/{id}/biosamples:  
    post:
      description: |
        Get the biosamples where this variant is found.
      operationId: getBiosamplesByVariantId
      tags:
        - Endpoints
      parameters:
        - name: id
          in: path
          description: Variant ID
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Request'
      responses:
        '200':
          description: |
            Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BiosampleResponse'
        '400':
          description: |
            Bad request (e.g. missing mandatory parameter)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BiosampleResponse'
        '401':
          description: >-
            Unauthorised (e.g. when an unauthenticated user tries to access a
            protected resource)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BiosampleResponse'
        '403':
          description: >-
            Forbidden (e.g. the resource is protected for all users or the user
            is authenticated but s/he is not granted for this resource)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BiosampleResponse'
  /g_variants/{id}/individuals:  
    post:
      description: |
        Get the individuals in which this variant is found.
      operationId: getIndividualsByVariantId
      tags:
        - Endpoints
      parameters:
        - name: id
          in: path
          description: Variant ID
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Request'
      responses:
        '200':
          description: |
            Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IndividualResponse'
        '400':
          description: |
            Bad request (e.g. missing mandatory parameter)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IndividualResponse'
        '401':
          description: >-
            Unauthorised (e.g. when an unauthenticated user tries to access a
            protected resource)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IndividualResponse'
        '403':
          description: >-
            Forbidden (e.g. the resource is protected for all users or the user
            is authenticated but they are not granted for this resource)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IndividualResponse'
