---
beacon_info:
  id: 'org.progenetix.beacon'
  name: 'Progenetix Cancer Genomics Beacon+'
  apiVersion: '2.0.pre.2020-04-07'
  version: 2020-04-07
  description:  |
    Beacon+ provides a forward looking implementation of the Beacon API, with focus on structural variants and metadata based on the cancer and reference genome profiling data represented in the Progenetix oncogenomic data resource (https://progenetix.org).
  welcomeUrl: 'https://beacon.progenetix.org/ui/'
  alternativeUrl: "https://progenetix.org"
  createDateTime: 2015-11-13
  updateDateTime: 2020-04-07
  organization:
    id: 'org.baudisgroup'
    name: 'baudisgroup at UZH and SIB'
    description: |
      The "Theoretical Cytogenetics and Oncogenomics" group at the University of Zurich (UZH) and the Swiss Institute of Bioinformatics (SIB) performs research in cancer genomics and provides bioinformatics tools and cancer genome data resources to the scientific community.
    address: "Department of Molecular Life Sciences, University of Zurich, Winterthurerstrasse 190, CH-8057 Zurich, Switzerland"
    welcomeUrl: 'https://info.baudisgroup.org'
    contactUrl: 'mailto:contact@progenetix.org'
    logoUrl: 'https://progenetix.org/p/progenetix.png'
  sampleAlleleRequests:
    - datasetIds:
        - arraymap
      requestType: variantCNVrequest
      assemblyId: GRCh38
      referenceName: '9'
      start:
        - 21000000
        - 21975098
      end:
        - 21967753
        - 25000000
      variantType: "DEL"
      filters:
        - "icdom-94403"
        - "icdot-C71"
    - datasetIds:
        - dipg
      assemblyId: GRCh38
      referenceName: '17'
      start:
        - 7577121
      alternateBases: "A"
      referenceBases: "G"
      filters:
        - "icdot-C71.7"
