# Bio-Metadata
NCIT:
  name: "National Cancer Institute Thesaurus"
  url: "https://ncit.nci.nih.gov/"
  db_key: 'biocharacteristics.type.id'
  scopes:
    biosamples:
      default: 1
    individuals:
      default: 0
  pattern: '^NCIT(\:C\d*?\-?)?$'
  examples:
    - 'NCIT:C27676'
    - 'NCIT:C9325'
  collation: biosubsets

UBERON:
  name: "Uberon cross-species anatomical structures ontology"
  url: "https://uberon.github.io"
  db_key: 'biocharacteristics.type.id'
  scopes:
    biosamples:
      default: 1
  pattern: '^UBERON(\:\d*?\-?)?$'
  examples:
    - 'UBERON:0000970'
    - 'UBERON:0035542'
  collation: biosubsets

MONDO:
  name: "Mondo Disease Ontology"
  url: "https://mondo.monarchinitiative.org"
  db_key: 'biocharacteristics.type.id'
  scopes:
    biosamples:
      default: 1
    individuals:
      default: 0
  pattern: '^MONDO([\:_]\d*?\-?)?$'
  examples:
    - 'MONDO:0002974'
    - 'MONDO:0012301'
  collation: biosubsets

HP:
  name: "Human Phenotype Ontology"
  url: "https://hpo.jax.org/"
  db_key: 'biocharacteristics.type.id'
  scopes:
    biosamples:
      default: 0
    individuals:
      default: 1
  pattern: '^HP(\:\d+?\-?)?$'
  examples:
    - 'HP:0012209'
  collation: biosubsets

PATO:
  name: "Phenotypic Qualities Ontology"
  url: "http://obofoundry.org/ontology/pato.html"
  db_key: 'biocharacteristics.type.id'
  scopes:
    biosamples:
      default: 0
    individuals:
      default: 1
  pattern: '^PATO(\:\d+?\-?)?$'
  examples:
    - 'PATO:0020000'
  collation: biosubsets

EFO:
  name: "Experimental Factor Ontology"
  url: "https://www.ebi.ac.uk/efo/"
  db_key: 'provenance.material.type.id'
  scopes:
    biosamples:
      default: 1
    individuals:
      default: 0
  pattern: '^EFO(\:\d+?\-?)?$'
  examples:
  collation: biosubsets
    - 'EFO:0009656'
  collation: biosubsets

icdom:
  name: "ICD-O 3 Morphologies (Progenetix)"
  url: "https://progenetix.org/"
  db_key: 'biocharacteristics.type.id'
  scopes:
    biosamples:
      default: 1
  pattern: '^icdom(\-\d{1,5}(\-\d{1,5})?)?$'
  examples:
    - 'icdom-85003'
    - 'icdom-94403'
  collation: biosubsets

icdot:
  name: "ICD-O 3 Topographies (Progenetix)"
  url: "https://progenetix.org/"
  db_key: 'biocharacteristics.type.id'
  scopes:
    biosamples:
      default: 1
  pattern: '^icdot(\-C\d\d?(\.\d)?\-?)?$'
  examples:
    - 'icdot-C42.2'
    - 'icdot-C54.1'
    - 'icdot-C5'
  collation: biosubsets

# Procedural Metadata

PMID:
  name: "NCBI PubMed"
  url: "https://www.ncbi.nlm.nih.gov/pubmed/"
  db_key: 'external_references.type.id'
  scopes:
    biosamples:
      default: 1
  pattern: '^(PMID)?\:(\d+?)?$'
  examples:
    - 'PMID:28966033'
    - 'PMID:9405679'
  collation: datacollections

geogse:
  name: "NCBI Gene Expression Omnibus Series"
  url: "https://www.ncbi.nlm.nih.gov/geo/"
  db_key: 'external_references.type.id'
  scopes:
    callsets:
      default: 0
    biosamples:
      default: 1
  pattern: '^geogse(\-GSE\d+?)?$'
  examples:
    - 'geogse-GSM253289'
  collation: datacollections

# geogsm:
#   name: "NCBI Gene Expression Omnibus Experiment" 
#   url: "https://www.ncbi.nlm.nih.gov/geo/"
#   db_key: 'external_references.type.id'
#   scopes:
#     callsets:
#       default: 0
#     biosamples:
#       default: 1
#   pattern: '^geogsm\-GSM\d+?$'
#   examples:
#     - 'geogsm-GSM253289'

# tcga:
#   name: "The Cancer Genome Atlas"
#   url: "http://cancergenome.nih.gov"
#   db_key: 'external_references.type.id'
#   scopes:
#     callsets:
#       default: 0
#     biosamples:
#       default: 1
#     individuals:
#       db_key: 'external_references.type.id'
#   pattern: '^tcga:[\-\w]+?$'
#   examples:
#     - 'tcga:000002fc-53a0-420e-b2aa-a40a358bba37'

geogpl:
  name: "NCBI Gene Expression Omnibus Platform"
  url: "https://www.ncbi.nlm.nih.gov/geo/"
  db_key: 'external_references.type.id'
  scopes:
    callsets:
      default: 0
    biosamples:
      default: 0
      default: 1
  pattern: '^geopl(\-GPL\d+?)?$'
  examples:
    - 'geogpl-GPL6504'
  collation: datacollections

cellosaurus:
  name: "Cellosaurus - a knowledge resource on cell lines"
  url: "https://web.expasy.org/cellosaurus/"
  db_key: 'external_references.type.id'
  scopes:
    callsets:
      default: 0
    biosamples:
      default: 1
  pattern: '^cellosaurus(\:CVCL_\w+?)?$'
  examples:
    - 'cellosaurus:CVCL_1650'
    - 'cellosaurus:CVCL_0006'
  collation: datacollections
