parameters:
  dataset_ids:
    type: array
    default:
      - progenetix
  response_type:
    type: string
    default: return_phenopackets
  variant_format:
    type: string
    default: progenetix
defaults:
  dataset_ids:
    - progenetix
  response_type: return_individuals
  variant_format: digest
variant_formats:
  - digest
  - progenetix
