---
h->o_types:
  cnvhistogram:
    id: 'pgx:handover:cnvhistogram'
    label: "CNV Histogram"
    description: "create a CNV histogram from matched callsets"
    h->o_key: 'cs._id'
    script_path_web: '/cgi-bin/beacondeliver.cgi'
  biosamplesdata:
    id: 'pgx:handover:biosamplesdata'
    label: "Biosamples"
    description: "retrieve data of the biosamples matched by the query"
    h->o_key: 'bs._id'
    script_path_web: '/services/deliveries'
  phenopackets:
    id: 'pgx:handover:phenopackets'
    label: "Phenopackets"
    description: "retrieve data of the phenopackets matched by the query"
    h->o_key: 'bs._id'
    # TODO: switch to /services/deliveries only w/ accessid (self scoping)
    # here, phenopackets actually want individuals; however, the phenopackets
    # service resolves this itself by forcing the retrieval of the matching
    # individuals 
    script_path_web: '/services/phenopackets'
  individualsdata:
    id: 'pgx:handover:individualsdata'
    label: "Individuals"
    description: "retrieve data of the individuals matched by the query"
    h->o_key: 'is._id'
    script_path_web: '/services/deliveries'
  variantsdata:
    id: 'pgx:handover:variantsdata'
    label: "Variants"
    description: "retrieve variants matched by the query"
    h->o_key: 'vs._id'
    script_path_web: '/cgi-bin/beacondeliver.cgi'
  callsetsvariants:
    id: 'pgx:handover:callsetsvariants'
    label: "Callsets Variants"
    description: "export all variants of matched callsets - potentially huge dataset..."
    h->o_key: 'cs._id'
    script_path_web: '/cgi-bin/beacondeliver.cgi'
  UCSClink:   
    id: 'pgx:handover:bedfile2ucsc'
    label: "Variants in UCSC"
    description: "map variants matched by the query to the UCSC browser"
    h->o_key: 'vs._id'
    ext_url: 'http://genome.ucsc.edu/cgi-bin/hgTracks?org=human&db=hg38'
    remove_subdomain: True
  # queryaggregation:
  #   id: 'pgx:handover:queryaggregation'
  #   label: "Aggregate Query"
  #   description: "Start new query limited to the current samples"
  #   h->o_key: 'cs._id'
  #   script_path_web: 'http://beacon.progenetix.org/ui/'
h->o_methods:
  bs._id:
    source_collection: biosamples
    source_key: _id
    target_collection: biosamples
    target_key: _id
  bs.id:
    source_collection: biosamples
    source_key: id
    target_collection: biosamples
    target_key: id
  bs.isid->bs.id:
    source_collection: biosamples
    source_key: individual_id
    target_collection: biosamples
    target_key: id
  bs.isid->is.id:
    source_collection: biosamples
    source_key: individual_id
    target_collection: individuals
    target_key: id
  cs.id:
    source_collection: callsets
    source_key: id
    target_collection: callsets
    target_key: id
  cs._id:
    source_collection: callsets
    source_key: _id
    target_collection: callsets
    target_key: _id
  cs.bsid->bs.id:
    source_collection: callsets
    source_key: biosample_id
    target_collection: biosamples
    target_key: id
  is._id:
    source_collection: individuals
    source_key: _id
    target_collection: individuals
    target_key: _id
  is.id:
    source_collection: individuals
    source_key: id
    target_collection: individuals
    target_key: id
  vs._id:
    source_collection: variants
    source_key: _id
    target_collection: variants
    target_key: _id
  vs.bsid->bs.id:
    source_collection: variants
    source_key: biosample_id
    target_collection: biosamples
    target_key: id
  vs.csid->cs.id:
    source_collection: variants
    source_key: callset_id
    target_collection: callsets
    target_key: id
  vs.digest:
    source_collection: variants
    source_key: digest
    target_collection: variants
    target_key: digest

