defaults:
  dataset_ids:
    - progenetix
  method: details
  response_type: return_biosamples
methods:
  ids:
    - id
  details:
    - id
    - description
    - biocharacteristics
    - external_references
    - provenance
    - info
  biocharacteristics:
    - id
    - description
    - biocharacteristics
  phenopackets:
    - id

