defaults:
  dataset_ids:
    - progenetix
  method: children
  filters:
    - NCIT
    - icdom
    - icdot
methods:
  children:
    - id
    - label
    - count
    - child_terms
  paths:
    - id
    - label
    - count
    - child_terms
    - hierarchy_paths
  counts:
    - id
    - label
    - count
  codematches:
    - id
    - label
    - code_matches
  cnvFrequencies:
    - id
    - label
    - frequencymaps
  codes:
    - id
    - label

