arg_pars:

  cytoBands: cytobands
  chroBases: chrobases
  assemblyId: genome

default_parameters:

  assemblyId:
    type: string
    pattern: '^\w+?[-\.]?\w+?$'
    default: GRCh38
    allowed:
      - "GRCh38"
      - "GRCh37"
      - "hg19"
      - "NCBI36"
      - "hg18"
      - "NCBI35"
      - "hg17"
      - "NCBI34"
      - "hg16"

  species:
    type: string
    pattern: '^\w[^\:]+?(\:[^\:]+)?$'
    default: 'taxonomy:9606'

request_types:
     
  cytobands2chrobases:
    parameters:
      cytoBands:
        pattern: ^(chro?)?([12]?[\dXY])([pq]((ter)|(cen)|([1-4]([0-8](\.\d\d*?)?)?)?))?\-?([pq]((ter)|(cen)|([1-4]([0-8](\.\d\d*?)?)?)?))?$
        type: string
        components:
          chr:
            regexi: 2
            pattern: '^(chro?)?[12]?[\dXY]$'
            type: string
          start:
            regexi: 3
            pattern: '^[pq]((ter)|(cen)|([1-4]([0-8](\.\d\d*?)?)?)?)$'
            type: string
          end:
            regexi: 10
            pattern: '^[pq]((ter)|(cen)|([1-4]([0-8](\.\d\d*?)?)?)?)$'
            type: string
    all_of:
      - assemblyId
      - cytoBands
  
  chrobases2cytobands:
    parameters:
      chroBases:
        pattern: ^(chro?)?([12]?[\dXY])\:(\d+?)(\-(\d+?))?$
        type: string
        examples:
          - "17:12000000-194418991"
        components:
          chr:
            regexi: 2
            pattern: '^(chro?)?[12]?[\dXY]$'
            type: string
          start:
            regexi: 3
            pattern: '^\d+?$'
            type: integer
          end:
            regexi: 5
            pattern: '^\d+?$'
            type: integer
    all_of:
      - assemblyId
      - chr
      - start
      - end

  chromosomeLocation2chrobases:
    parameters:
      type:
        type: string
        pattern: 'ChromosomeLocation'
        default: 'ChromosomeLocation'
      chr:
        type: string
        pattern: '^(chro?)?[XYxy\d]\d?$'
      start:
        type: string
        pattern: '^[pq]((ter)|(cen)|([1-4]([0-8](\.\d\d*?)?)?)?)$'
      end:
        type: string
        pattern: '^[pq]((ter)|(cen)|([1-4]([0-8](\.\d\d*?)?)?)?)$'
    all_of:
      - assemblyId
      - type
      - species
      - chr
      - start
      - end

