parameters:

  assemblyId:
    type: string
    pattern: '^\w+?[\w\-\.]*?\w*?$' # for 2019-nCoV
    default: GRCh38

  referenceName:
    type: string
    pattern: '^\w+?[\w\-]*?\w*?$' # for 2019-nCoV

  mateName:
    type: string
    pattern: '^([1-9]|1\d|2[0-4]|[XY]|MT)$'

  referenceBases:
    type: string
    pattern: '^[ACGTN]+$'

  alternateBases:
    type: string
    pattern: '^[ACGTN]+$'

  variantType:
    type: string
    pattern: '^((:?DUP)|(:?DEL)|(:?BND)|(:?INS)|(:?INV)|(:?CNV)|(:?INDEL)|(:?SNP)|(:?SNV))$'

  start:
    type: array
    items:
      type: integer
      pattern: '^\d+?$'

  end:
    type: array
    items:
      type: integer
      pattern: '^\d+?$'

# custom parameters

  cytoBands:
    pattern: ^(chro?)?([12]?[\dXY])([pq]((ter)|([1-4]([0-8](\.\d\d*?)?)?)?))?\-?([pq]((ter)|([1-4]([0-8](\.\d\d*?)?)?)?))?$
    type: string

  chroBases:
    pattern: ^(chro?)?([12]?[\dXY])\:(\d+?)(\-(\d+?))?$
    type: string

  rangeTag:
    type: string
    pattern: 'true'

BeaconRequestTypes:

  g_variant:

    variantIdRequest:
      description:
        A query for a specific variant by its `id`.
      all_of:
        - id

    variantAlleleRequest:
      description: |
        This type corresponds to the original BeaconAlleleRequest, in which at a
        specified genome position a query looks for a combination of reference and
        replacement base(s).
      all_of:
        - assemblyId
        - referenceName
        - start
        - referenceBases
        - alternateBases

    variantCNVrequest:
      description: |
        This specific request allows for the bracketed search of genomic variants
        with start and end coordinates and a variant type. in contrast to a
        beaconRangeRequest, the start and end positions of the matched variants 
        have to fall into the (1 base or longer) intervals for start and end,
        respectively (while for the range request variants falling between start
        and end are being matched).
        `start` and `end` parameters are lists of 1 or 2 integers. The most common
        use here would be a use of 2 integers both for start and end, to allow
        fuzzy matching of CNVs and similar variants of imprecise length and
        position.
      all_of:
        - assemblyId
        - referenceName
        - start
        - end
        - variantType

    variantFusionRequest:
      description: |
        This request is similar to the CNV request in using possibly fuzzy
        intervals for start and end of structural variants. However, here the
        "end" position refers to the fusion partner on the same or different
        chromosome as specified through "mateName".
        Conventions:
        * `mateName` can be the same or different to `referenceName`
        * `mateName` is the higher numbered/named chromosome
      all_of:
        - assemblyId
        - referenceName
        - mateName
        - start
        - end

    variantRangeRequest:
      description: |
        The beaconRangeRequest queries variants falling between start and end.
        `start` and `end` parameters should be single values.
      all_of:
        - assemblyId
        - referenceName
        - start
        - end
      optional:
        - variantType
        - referenceBases
        - alternateBases

# disambiguation of legacy requests

request_types:

  variantCNVrequest:
    all_of:
      - assemblyId
      - start
      - end
      - referenceName
      - variantType
    
  variantRangeRequest:
    all_of:
      - assemblyId
      - start
      - end
      - referenceName
    # one_of:
    #   - variantType
    #   - alternateBases
    
  variantAlleleRequest:
    all_of:
      - assemblyId
      - start
      - referenceName
      - referenceBases
      - alternateBases

# custom
     
  cytobands2positions_request:
    all_of:
      - assemblyId
      - cytoBands
  
  positions2cytobands_request:
    all_of:
      - assemblyId
      - start
      - end
      - referenceName
      - rangeTag

  ChromosomeLocation:
    all_of:
      - type
      - species
      - chr
      - start
      - end





